version: "3.9"

services:
  growing-up:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8501:8501"
    volumes:
      - ./weights:/app/weights
      - ./outputs:/app/outputs
      - ./tmp:/app/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    shm_size: "8gb"
